apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: proxy-pod
        {{ if .Values.proxy.labels -}}
        # Because toYaml + indent is super flaky
        {{ range $key, $value := .Values.proxy.labels -}}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      annotations:
        # This lets us autorestart when the configmap changes!
        checksum/config-map: {{ include (print $.Template.BasePath "/proxy/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
      - configMap:
          defaultMode: 420
          name: traefik-config-{{ default .Release.Revision .Values.revisionOverride }}
        name: config
      containers:
      - name: proxy-container
        image: traefik:1.3.3
        args:
          - --configfile=/config/traefik.toml
        resources:
{{ toYaml .Values.proxy.resources | indent 12 }}
        env:
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: hub-secret
                key: proxy.token
        imagePullPolicy: {{ .Values.proxy.imagePullPolicy }}
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
          - containerPort: 8000
            name: proxy-public
